name: tic_tac_toe
description: A tic tag toe game

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+7
  cloud_firestore: ^0.12.7
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Crackman
      fonts:
        - asset: res/fonts/crackman.ttf